Data loaded: there are 60000 images.
model and optimizer are ready.
Starting clippo training !
/home/temp/miniconda3/envs/stanford_env/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py:2387: UserWarning: torch.distributed._all_gather_base is a private function and will be deprecated. Please use torch.distributed.all_gather_into_tensor instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/temp/Desktop/KD/CLIPPO/train.py", line 167, in <module>
    main(args)
  File "/home/temp/Desktop/KD/CLIPPO/train.py", line 125, in main
    loss = train_one_epoch(clippo, data_loader, optimizer,
  File "/home/temp/Desktop/KD/CLIPPO/train.py", line 33, in train_one_epoch
    l1, l2 = loss_dino(logits_per_text, logits_per_image)
  File "/home/temp/miniconda3/envs/stanford_env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/temp/Desktop/KD/CLIPPO/tim_and_bert.py", line 86, in forward
    image_centered = F.softmax((image_logit - self.center), dim=-1)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!