2023-08-21 12:25:23,511 INFO    MainThread:3384971 [wandb_setup.py:_flush():76] Configure stats pid to 3384971
2023-08-21 12:25:23,511 INFO    MainThread:3384971 [wandb_setup.py:_flush():76] Loading settings from /home/temp/.config/wandb/settings
2023-08-21 12:25:23,511 INFO    MainThread:3384971 [wandb_setup.py:_flush():76] Loading settings from /home/temp/Desktop/projects/KD/CLIPPO/wandb/settings
2023-08-21 12:25:23,511 INFO    MainThread:3384971 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-08-21 12:25:23,511 INFO    MainThread:3384971 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-08-21 12:25:23,511 INFO    MainThread:3384971 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'CLIPPO/train.py', 'program': '/home/temp/Desktop/projects/KD/CLIPPO/train.py'}
2023-08-21 12:25:23,511 INFO    MainThread:3384971 [wandb_init.py:_log_setup():507] Logging user logs to /home/temp/Desktop/projects/KD/CLIPPO/wandb/run-20230821_122523-zbvh14u5/logs/debug.log
2023-08-21 12:25:23,511 INFO    MainThread:3384971 [wandb_init.py:_log_setup():508] Logging internal logs to /home/temp/Desktop/projects/KD/CLIPPO/wandb/run-20230821_122523-zbvh14u5/logs/debug-internal.log
2023-08-21 12:25:23,511 INFO    MainThread:3384971 [wandb_init.py:init():547] calling init triggers
2023-08-21 12:25:23,511 INFO    MainThread:3384971 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'learning_rate': 1.5625e-05, 'architecture': 'CLIPPO', 'dataset': 'CC3M_test', 'epochs': 50}
2023-08-21 12:25:23,511 INFO    MainThread:3384971 [wandb_init.py:init():595] starting backend
2023-08-21 12:25:23,511 INFO    MainThread:3384971 [wandb_init.py:init():599] setting up manager
2023-08-21 12:25:23,514 INFO    MainThread:3384971 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-08-21 12:25:23,515 INFO    MainThread:3384971 [wandb_init.py:init():605] backend started and connected
2023-08-21 12:25:23,517 INFO    MainThread:3384971 [wandb_init.py:init():695] updated telemetry
2023-08-21 12:25:23,561 INFO    MainThread:3384971 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-08-21 12:25:24,309 INFO    MainThread:3384971 [wandb_run.py:_on_init():2176] communicating current version
2023-08-21 12:25:24,672 INFO    MainThread:3384971 [wandb_run.py:_on_init():2185] got version response upgrade_message: "wandb version 0.15.8 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-08-21 12:25:24,672 INFO    MainThread:3384971 [wandb_init.py:init():782] starting run threads in backend
2023-08-21 12:25:29,870 WARNING MainThread:3384971 [wandb_init.py:init():1167] interrupted
Traceback (most recent call last):
  File "/home/temp/miniconda3/envs/stanford_env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1145, in init
    run = wi.init()
  File "/home/temp/miniconda3/envs/stanford_env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 794, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/temp/miniconda3/envs/stanford_env/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/home/temp/miniconda3/envs/stanford_env/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/home/temp/miniconda3/envs/stanford_env/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/home/temp/miniconda3/envs/stanford_env/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/home/temp/miniconda3/envs/stanford_env/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/temp/miniconda3/envs/stanford_env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1153, in init
    getcaller()
  File "/home/temp/miniconda3/envs/stanford_env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 832, in getcaller
    print("Problem at:", src, line, func)
  File "/home/temp/Desktop/projects/KD/CLIPPO/utils.py", line 463, in print
    builtin_print(*args, **kwargs)
KeyboardInterrupt
