Data loaded: there are 500 images.
model and optimizer are ready.
Starting clippo training !
Exception ignored in: <function _releaseLock at 0x7f7ddcceb820>
Traceback (most recent call last):
  File "/home/temp/miniconda3/envs/stanford_env/lib/python3.9/logging/__init__.py", line 227, in _releaseLock
    def _releaseLock():
